services:
  accounts:
    image: "jayaedde/accounts-service:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - communityBank



  cards:
    image: "jayaedde/cards-service:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - communityBank

  loans:
    image: "jayaedde/loans-service:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - communityBank

networks:
  communityBank:
    driver: "bridge"
